### ISSUE TITLE
How to create multiple links on Wistar between devices?

### ISSUE THREAD

**Issue by akher1** [Juniper/wistar#50]
I need to create multiple links between devices to recreate the MC-LAG, Virtual chassis setup.
Kindly advice me how can we do that in WISTAR for vQFX10k.

**Comment by dmontagner** [comment]
@akher1 while you can create multiple links between two objects (vMX, vQFX, VMs, etc), setting up MC-LAG will require some low level hacking in the host system.

In order to add two links between two vQFXes, first add both vQFX to Wistar. Then, create the first link between them. Double-click on the first link and drag it to the left or right. Then you will be able to add the second link. See attached picture.

<img width="461" alt="Screen Shot 2019-08-02 at 05 20 51" src="https://user-images.githubusercontent.com/4936154/62321370-ceb52800-b4e5-11e9-9ae5-c6834ad5580c.png">

As for MC-LAG, you will need some low level hacking in the host OS because the Linux kernel does not allow (by default) forwarding of multicast MAC address for some of the LAG function. Similar issue happens if you want to enable LLDP in the virtual topology. In order to enable these functions, you will need to download the kernel sources, make a small modification, recompile the kernel and boot your host OS with the modified kernel.

The issue is explained in this blog: https://interestingtraffic.nl/2017/11/21/an-oddly-specific-post-about-group_fwd_mask/

The main problem is that you won't be able to set certain values for group_fwd_mask. The developers of this part of the kernel hard-coded a protection because setting the group_fwd_mask to a very permissive setting will expose your system to potential loops. So, the change you need to do in the kernel is to remove that protection.

**Comment by akher1** [comment]
Thanks, it works for me.

Thanks again.

Regards,
Ankur
